name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Linux_Build:

    runs-on: cpp

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
  
  Mac_Build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
